import "./globals.css";
import { Work_Sans } from "next/font/google";
const work_Sans = Work_Sans({ subsets: ["latin"] });

export const metadata = {
  title: "Dashboard || HairCutt Expresss",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={work_Sans.className}>{children}</body>
    </html>
  );
}
